### ISSUE TITLE
Use single quotes to avoid double-quote escaping

### ISSUE THREAD

**Issue by leoshimo** [leoshimo/feedbinctl#10]
Use single quotes in search queries to avoid the need for double-quote escaping.

Example:
```toml
[[searches]]
name = "Model Context Protocol"
query = "MCP OR modelcontextprotocol OR \"model context protocol\" "
```

Should be:
```toml
[[searches]]
name = 'Model Context Protocol'
query = 'MCP OR modelcontextprotocol OR "model context protocol"'
```

This makes the configuration cleaner and easier to read.
